variables:
  JAVA_VERSION: 17

default:
  image: $AWS_ECR_REPOSITORY/landbay/devops/ci/ci-pipeline-images/backend:$JAVA_VERSION

stages:
  - build

build_backend:
  extends:
    - .gitlab-eks-lg-build
  stage: build
  script:
    - echo "hello world"
    - cd backend
    - ./gradlew build --no-daemon

build_frontend:
  stage: build
  script:
    - echo "hello world"
    - cd frontend
    - npm install
    - npm run build