include:
  - project: "landbay/devops/ci/ci_pipeline"
    ref: "master"
    file: gitlab-eks/common/gitlab_eks_resources.yml

variables:
  JAVA_VERSION: 17
  NODE_VERSION: 20

stages:
  - build
  - deploy

build_and_push_image:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  extends:
    - .gitlab-eks-lg-build
  stage: package
  variables:
    BASE_REPOSITORY_PATH: "${AWS_ECR_REPOSITORY}/landbay/${CI_PROJECT_NAME}"
    TAG_MR_PREFIX: "ci-${CI_COMMIT_REF_NAME}"
    TAG_BUILD_PREFIX: "ci-${CI_COMMIT_REF_NAME}-${CI_JOB_ID}"
  before_script:
    - source ./.ci/init-kaniko.sh
  script:
    - echo $BASE_REPOSITORY_PATH
    - echo $TAG_MR_PREFIX
    - echo $TAG_BUILD_PREFIX
    - /kaniko/executor --context . --dockerfile "Dockerfile" --destination ${BASE_REPOSITORY_PATH}":"${TAG_MR_PREFIX}


#DEPLOY TO UAT

#DEPLOY TO PROD