include:
  - project: "landbay/devops/ci/ci_pipeline"
    ref: "master"
    file: gitlab-eks/common/gitlab_eks_resources.yml

variables:
  JAVA_VERSION: 17
  NODE_VERSION: 14

default:
  image: $AWS_ECR_REPOSITORY/landbay/devops/ci/ci-pipeline-images/backend:$JAVA_VERSION

stages:
  - build

#build_backend:
#  extends:
#    - .gitlab-eks-lg-build
#  stage: build
#  script:
#    - echo "hello world"
#    - cd backend
#    - ./gradlew build -x kaptTestKotlin -x compileTestKotlin --no-daemon

build_frontend:
  image: $AWS_ECR_REPOSITORY/landbay/devops/ci/ci-pipeline-images/frontend:$NODE_VERSION
  stage: build
  script:
    - echo "hello world"
    - cd frontend
    - npm install
    - npm run build