include:
  - project: "landbay/devops/ci/ci_pipeline"
    ref: "master"
    file: gitlab-eks/common/gitlab_eks_resources.yml

variables:
  JAVA_VERSION: 17
  NODE_VERSION: 20

stages:
#  - build
  - package

#build_backend:
#  image: $AWS_ECR_REPOSITORY/landbay/devops/ci/ci-pipeline-images/backend:$JAVA_VERSION
#  extends:
#    - .gitlab-eks-lg-build
#  stage: build
#  script:
#    - cd backend
#    - ./gradlew build -x kaptTestKotlin -x compileTestKotlin --no-daemon
#  artifacts:
#    paths:
#      - backend/build/libs/*.jar
#    expire_in: 1 day
#
#build_frontend:
#  image: $AWS_ECR_REPOSITORY/landbay/devops/ci/ci-pipeline-images/frontend:$NODE_VERSION
#  extends:
#    - .gitlab-eks-lg-build
#  stage: build
#  script:
#    - cd frontend
#    - npm install
#    - npm run build

construct_container:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  extends:
    - .gitlab-eks-lg-build
  stage: package
  variables:
    BASE_REPOSITORY_PATH: "${AWS_ECR_REPOSITORY}/landbay/${CI_PROJECT_NAME}"
    TAG_MR_PREFIX: "ci-${CI_COMMIT_REF_NAME}"
    TAG_BUILD_PREFIX: "ci-${CI_COMMIT_REF_NAME}-${CI_JOB_ID}"
  before_script:
#    - source ./common/functions/init-kaniko.sh
  script:
    - echo $BASE_REPOSITORY_PATH
    - echo $TAG_MR_PREFIX
    - echo $TAG_BUILD_PREFIX
#    - /kaniko/executor --context . --dockerfile "Dockerfile" --destination TODO-ECR-REPO


#DEPLOY TO UAT

#DEPLOY TO PROD