include:
  - project: "landbay/devops/ci/ci_pipeline"
    ref: "master"
    file: gitlab-eks/common/gitlab_eks_resources.yml

variables:
  JAVA_VERSION: 17
  NODE_VERSION: 20

stages:
  - build

build_backend:
  image: $AWS_ECR_REPOSITORY/landbay/devops/ci/ci-pipeline-images/backend:$JAVA_VERSION
  extends:
    - .gitlab-eks-lg-build
  stage: build
  script:
    - cd backend
    - ./gradlew build -x kaptTestKotlin -x compileTestKotlin --no-daemon

build_frontend:
  image: $AWS_ECR_REPOSITORY/landbay/devops/ci/ci-pipeline-images/frontend:$NODE_VERSION
  extends:
    - .gitlab-eks-lg-build
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build