spring:
  liquibase:
    change-log: classpath:changelog/000-changelog.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/kviklet
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
app:
  name: "Kviklet"
cors:
  allowedOrigins: "http://localhost:5173"
aws:
  secretsmanager:
    enabled: false